---
- name: Install Python Software Properties
  apt: name=python-software-properties state=present update_cache=yes

- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable'

- name: Update apt-cache
  apt: update_cache=yes

- name: Install Nignx
  apt: name=nginx state=present
  register: debug_nginx
  notify: start nginx




- debug: msg="Debug of task 1 - Install Nginx {{ debug_nginx }}"